### ISSUE TITLE
Necessidade de dados do servidor

### ISSUE THREAD

**Issue by ghost** [rede-sustentabilidade/site-wordpress#13]
Olá,

Preciso dos dados FTP do site para upar o hotsite do congresso. Caso prefira me passar o por e-mail, skype ou telefone(whatapp) , segue: 

marco.aureliostd@gmail.com 
61 93480555

**Comment by lpirola** [comment]
@marcostd existe um padrão que as aplicações devem seguir, podemos conversar e te explico como é possível realizar publicações no servidor da Rede.
