### ISSUE TITLE
Desatrelar confirmação de filiado de e-mails regionais

### ISSUE THREAD

**Issue by thomaskp** [rede-sustentabilidade/site-wordpress#15]

**Comment by lpirola** [comment]
Não tem nenhum filiado ou usuário utilizando e-mail estadual (uf@redesustentabilidade.org.br) para fazer login e por isso nenhum deles conseguem fazer confirmação pois não conseguem logar.

Na tarefa #17 removemos a funcionalidade de fazer isso pelas listas, agora só é possível fazer pelo admin do wordpress.
