### ISSUE TITLE
Ajuste no menu para incluir rápida explicação

### ISSUE THREAD

**Issue by thomaskp** [rede-sustentabilidade/site-wordpress#22]

**Comment by lpirola** [comment]
![fluxo-filiacao_3-logado-submenu](https://cloud.githubusercontent.com/assets/14948/13222656/ae5bcee8-d95f-11e5-98a1-23571fe910f8.png)

**Comment by lpirola** [comment]
O layout será replicado para todos os itens do menu, inclusive os que aparecem quando logado. Isso está parado por conta do texto necessário.

**Comment by thedanheller** [comment]
Aguardo o texto final?

**Comment by lpirola** [comment]
Segue os textos:

Meu perfil (tem como ocultar? se tiver bom, se não proponho o texto abaixo)
Ainda estamos em construção! Logo menos, por este link você irá poder editar seus dados pessoais.

Status
Aqui mostra seu status dentro da Rede. Há duas possibilidades APOIADOR ou FILIADO. 

Arquivos úteis
Neste link você poderá acessar os principais documentos internos da REDE.

Pré-Filiados aguardando abono (nós vamos retirar, mas mesmo assim fiz um texto provisório)
Esta é a lista de pessoas que acabaram de se registrar para ser um filiado à REDE. Qualquer filiado no Brasil pode abonar um pré-filiado à abonar

Pré-Filiados em fase de Impugnação
Toda pré-filiação deve estar disponível para contestação por qualquer filiado. A pré-filiação fica nesta lista por 15 dias.

Pré-Filiados à Confirmar
Lista dos pré-filiados que ainda precisam passar pela formação política para terem sua filiação confirmada.

Filiados
Esta é a lista de todos os filiados da REDE. Todas as pessoas que estão nessa lista também estão registradas pelo partido no FiliaWeb do TSE.

Debate: Teses e PRIFS
Ambiente da REDE para que os filiados possam debater as teses e PRIFs apresentadas no 2 Congresso da REDE.

Transmissão 2 Congresso
Link para participação da transmissão do 2 Congresso da REDE.
