### ISSUE TITLE
Corrigir fluxo de login

### ISSUE THREAD

**Issue by thomaskp** [rede-sustentabilidade/site-wordpress#24]
- Trocar texto "a url abaixo está solicitando acesso ao seu endereço de e-mail."
- Gravar aceite no passaporte.

**Comment by lpirola** [comment]
![fluxo-filiacao_1-deslogado](https://cloud.githubusercontent.com/assets/14948/13222668/b8da185c-d95f-11e5-8937-ed23d471e5d2.png)
![fluxo-filiacao_2-logado](https://cloud.githubusercontent.com/assets/14948/13222669/b8db9c5e-d95f-11e5-8905-0686a4c4c8d0.png)
