### ISSUE TITLE
Tem gente recebendo e-mail de filiado , sem tá filiado

### ISSUE THREAD

**Issue by ghost** [rede-sustentabilidade/site-wordpress#37]
E-mail de abono e filiação estão sendo disparados à pessoas com status 8

**Comment by ghost** [comment]
São enviado 4 e-mails, cujo os assunto são:
- Recebemos sua pré-filiação!
- Sua pré filiação foi  abonada!
- A sua pré-filiação está confirmada.
- Parabéns, sua filiação está confirmada! 

Vale lembrar que a fase de abono não existe mais, logo , ao meu ver,  não faz sentido o envio do email.

**Comment by lpirola** [comment]
@marcostd Esses são todos os e-mail enviados. Como você falou, o e-mail de abono não faz sentido enviar. O envio era feito apenas quando alguém alterava o status do usuário, isso acabou de ser desabilitado.
