### ISSUE TITLE
Backup e migração dos e-mail

### ISSUE THREAD

**Issue by lpirola** [rede-sustentabilidade/site-wordpress#43]

**Comment by lpirola** [comment]
criar e-mail executiva@rede agendanacional@rede

**Comment by stefanomartins** [comment]
Já existe a conta executivo@redesustentabilidade.org.br. A conta executiva@redesustentabilidade.org.br deve ser criada assim mesmo?

**Comment by lpirola** [comment]
não precisa, acredito, vou confirmar.
